---
title: "growth_curve_analysis_071223"
author: "Sierra Mellor"
date: "2023-06-30"
output: html_document
---

gcplyr walk-through: https://mikeblazanin.github.io/gcplyr/articles/gcplyr.html 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install Packages
Only need to install packages once

```{r}
install.packages("gcplyr")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("lubridate")
install.packages("ggpubr")
```

## Load Libraries
Load libraries every time

```{r, echo=FALSE}
library(gcplyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggpubr)
```

## Import and Transform Data
Save data in .csv format first

```{r}
## import data as wide format
# save data in csv format
# data is wide-shaped (each row is a timepoint, each column is a well from the pate)
wide_data_0803_plate1 <- read_wides("080323_gc_data_plate1.csv") # data from plate 1
wide_data_0803_plate2 <- read_wides("080323_gc_data_plate2.csv") # data from plate 2
wide_data_0803_plate3 <- read_wides("080323_gc_data_plate3.csv") # data from plate 3

## transform to tidy format
# tidy-shaped: each unique measurement has its own row
# use trans_wide_to_tidy, specify wide data frame and which columns are not data
tidy_data_0803_plate1 <- trans_wide_to_tidy(
  wides = wide_data_0803_plate1,
  id_cols = c("file", "Time"))

tidy_data_0803_plate2 <- trans_wide_to_tidy(
  wides = wide_data_0803_plate2,
  id_cols = c("file", "Time"))

tidy_data_0803_plate3 <- trans_wide_to_tidy(
  wides = wide_data_0803_plate3,
  id_cols = c("file", "Time"))

```

## Create Design Information

```{r}
# design for first plate
design_0803_plate1 <- make_design(
  output_format = "tidy", # set to "blocks" to check that it's correct, then save as "tidy"
  nrows = 8, ncols = 12, lookup_tbl_start = "A",
  Guide = list( 
    c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "empty"), # values
    2:7, # rows to apply to (those left out will be filled in with NA)
    2:10, # columns to apply to
    "AACCDD", # pattern of the values
    FALSE # indicate whether filled by row (TRUE) or by column (FALSE)
  ), # set design for guide
  ATC_uM = list( 
    c(0,0.4,1),
    2:7,
    2:10,
    "AAABBBCCC",
    TRUE
  ), # set design for ATC concentration
  Replicate = list(
    c(1,2,3),
    2:7,
    2:10,
    "ABC",
    TRUE
  ), # set design for replicates
  Vector = list(
    c("pidCas9", "pidSpryC"),
    2:7,
    2:10,
    "ABABAB",
    FALSE
  ), # set design for plasmid
    Gene = list(
    c("ftsZ", "dnaA", "fusA", "proS", "ftsB", "empty"),
    2:7,
    2:10,
    "A",
    FALSE
    ), # set design for gene
  PAM = list(
    c("NGG", "NAN", "NNN"),
    2:7,
    2:10,
    "AABBCC",
    FALSE
  )
) 

design_0803_plate2 <- make_design(
  output_format = "tidy", # set to "blocks" to check that it's correct, then save as "tidy"
  nrows = 8, ncols = 12, lookup_tbl_start = "A",
  Guide = list( 
    c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "empty"), # values
    2:7, # rows to apply to (those left out will be filled in with NA)
    2:10, # columns to apply to
    "HIJRRR", # pattern of the values
    FALSE # indicate whether filled by row (TRUE) or by column (FALSE)
  ), # set design for guide
  ATC_uM = list( 
    c(0,0.4,1),
    2:7,
    2:10,
    "AAABBBCCC",
    TRUE
  ), # set design for ATC concentration
  Replicate = list(
    c(1,2,3),
    2:7,
    2:10,
    "ABC",
    TRUE
  ), # set design for replicates
  Vector = list(
    c("pidCas9", "pidSpryC"),
    2:7,
    2:10,
    "AAAABA",
    FALSE
  ), # set design for plasmid
    Gene = list(
    c("ftsZ", "dnaA", "fusA", "proS", "ftsB", "empty"),
    2:7,
    2:10,
    "CCCFFF",
    FALSE
    ), # set design for gene
  PAM = list(
    c("NGG", "NAN", "NNN", "empty"),
    2:7,
    2:10,
    "ABCDDD",
    FALSE
  )
)


design_0803_plate3 <- make_design(
  output_format = "tidy", # set to "blocks" to check that it's correct, then save as "tidy"
  nrows = 8, ncols = 12, lookup_tbl_start = "A",
  Guide = list( 
    c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "empty"), # values
    2:7, # rows to apply to (those left out will be filled in with NA)
    2:10, # columns to apply to
    "NPQQRR", # pattern of the values
    FALSE # indicate whether filled by row (TRUE) or by column (FALSE)
  ), # set design for guide
  ATC_uM = list( 
    c(0,0.4,1),
    2:7,
    2:10,
    "AAABBBCCC",
    TRUE
  ), # set design for ATC concentration
  Replicate = list(
    c(1,2,3),
    2:7,
    2:10,
    "ABC",
    TRUE
  ), # set design for replicates
  Vector = list(
    c("pidCas9", "pidSpryC"),
    2:7,
    2:10,
    "AAABAB",
    FALSE
  ), # set design for plasmid
    Gene = list(
    c("ftsZ", "dnaA", "fusA", "proS", "ftsB", "empty"),
    2:7,
    2:10,
    "EEEEFF",
    FALSE
    ), # set design for gene
  PAM = list(
    c("NGG", "NAN", "NNN", "empty"),
    2:7,
    2:10,
    "ABCCDD",
    FALSE
  )
)

```

## Merge and Clean up Data

```{r}
# merge data and design data frames
data_design_0803_plate1 <- merge_dfs(tidy_data_0803_plate1, design_0803_plate1)
data_design_0803_plate2 <- merge_dfs(tidy_data_0803_plate2, design_0803_plate2)
data_design_0803_plate3 <- merge_dfs(tidy_data_0803_plate3, design_0803_plate3)


# put together data from the two plates (use to plot all data together)
data_design_0803_all <- rbind(data_design_0803_plate1, data_design_0803_plate2, data_design_0803_plate3)

# convert time to numeric
# hms() since data has hours, minutes, and seconds (use hm() for hours & minutes)
# set unit to be hours (defaults to seconds)
data_design_0803_all$Time <- time_length(hms(data_design_0803_all$Time), unit = "hour")


# reorder Well, Guide, Gene, and PAM levels so they appear in the correct order
# this part generates A1-H12: paste(rep(LETTERS[1:8], each=12), 1:12, sep="")
data_design_0803_all$Well <- factor(data_design_0803_all$Well,
                                       levels=paste(rep(LETTERS[1:8], each=12), 1:12, sep=""))
data_design_0803_all$Guide <- factor(data_design_0803_all$Guide,
                                        levels=c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "empty"))

data_design_0803_all$Gene <- factor(data_design_0803_all$Gene, levels = c("ftsZ", "dnaA", "fusA", "proS", "ftsB", "empty"))

data_design_0803_all$PAM <- factor(data_design_0803_all$PAM, levels = c("NGG", "NAN", "NNN", "empty"))

# omit NA wells (use to plot only experimental wells)
data_design_0803_filtered <- data_design_0803_all %>%
  filter(!is.na(Guide))

# exclude other data if needed (contamination, etc)

# regenerate separate tables for plates 1 and 2 (use to plot plates separately)
data_design_0803_plate1 <- data_design_0803_filtered %>%
  filter(file=="080323_gc_data_plate1")

data_design_0803_plate2 <- data_design_0803_filtered %>%
  filter(file=="080323_gc_data_plate2")

data_design_0803_plate3 <- data_design_0803_filtered %>%
  filter(file=="080323_gc_data_plate3")


# average replicates together
data_design_0803_averages <- data_design_0803_filtered %>%
  group_by(Time, Guide, ATC_uM, Vector, Gene, PAM) %>%
  summarize(Average = mean(Measurements)) %>%
  ungroup()

```

## Plot Curves

```{r}
# labels for ATC concentration
ATC_labs <- c("0 uM", "0.4 uM", "1 uM")
names(ATC_labs) <- c("0", "0.4", "1")

# labels for guides - choose one depending on how you want plot to look
guide_labs <- c("Guide 10 (NGG)", "Guide 11 (NAN)", "Guide 12 (NAN)", "Guide 13 (NNN)", 
                "Guide 14 (NGG)", "Guide 15 (NAN)", "Guide 16 (NNN)", "Guide 17 (NGG)",
                "Guide 18 (NAN)", "Guide 19 (NNN)", "Guide 20 (NGG)", "Guide 21 (NAN)",
                "Guide 22 (NNN)", "Guide 23 (NGG)", "Guide 24 (NAN)", "Guide 25 (NAN)", "Guide 26 (NNN)", "Empty")

guide_labs <- c( "NGG", "NAN", "NAN", "NNN", "NGG", "NAN", "NNN", "NGG", "NAN", "NNN", "NGG", "NAN", "NNN", "NGG", "NAN", "NAN", "NNN", "Empty")

guide_labs <- c("Guide 10", "Guide 11", "Guide 12", "Guide 13", 
                "Guide 14", "Guide 15", "Guide 16", "Guide 17",
                "Guide 18", "Guide 19", "Guide 20", "Guide 21",
                "Guide 22", "Guide 23", "Guide 24", "Guide 25", "Guide 26", "empty")

guide_labs <- c("ftsZ NGG", "ftsZ NAN", "ftsZ NAN", "ftsZ NNN",
                "dnaA NGG", "dnaA NAN", "dnaA NNN", 
                "fusA NGG", "fusA NAN", "fusA NNN", 
                "proS NGG", "proS NAN", "proS NNN", 
                "ftsB NGG", "ftsB NAN", "ftsB NAN", "ftsB NNN", "Empty")

names(guide_labs) <- c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "empty")

# plot by well - plate 1 (just to take a look at data)
ggplot(data = data_design_0803_plate1, aes(x=Time, y=Measurements, color = ATC_uM)) +
  geom_line() +
  facet_wrap(~Well, nrow = 6, ncol = 9)

# plot by well - plate 2 (just to take a look at data)
ggplot(data = data_design_0803_plate2, aes(x=Time, y=Measurements, color = ATC_uM)) +
  geom_line() +
  facet_wrap(~Well, nrow = 6, ncol = 9)

ggplot(data = data_design_0803_plate3, aes(x=Time, y=Measurements, color = ATC_uM)) +
  geom_line() +
  facet_wrap(~Well, nrow = 6, ncol = 9)


# plot with everything
growth_curve_plot_0803 <- ggplot(data = data_design_0803_filtered, aes(x=Time, y=Measurements, color = Replicate)) +
  geom_smooth(span=0.15, se=FALSE) +
  facet_grid(rows=vars(Gene, Guide), cols = vars(Vector, ATC_uM),
             labeller = labeller(ATC_uM = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "Guides 10-26 Growth Assay", caption = "From Aug 3, 2023") +
  theme_bw() +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

# save plot
ggsave("080323_growthcurves.png", plot =growth_curve_plot_0726)


# plot with averages of replicates
growth_curve_averages_0803 <- ggplot(data = data_design_0803_averages, aes(x=Time, y=Average, color = ATC_uM)) +
  geom_smooth(span=0.15, se=FALSE) +
  facet_wrap(~Gene + Vector + Guide, ncol = 3,
             labeller = labeller(ATC_uM = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "Guides 10-26 Growth Assay", caption = "From Aug 3, 2023") +
  theme_bw() +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

# save plot
ggsave("080323_growthcurves_average.png", plot = growth_curve_averages_0803)

# add color specification
data_design_0803_averages <- data_design_0803_averages %>%
  mutate(Group = case_when(Guide == "empty" ~ "Empty",
                           Guide != "empty" ~ "Experimental"))

# set up dataset that will allow for plotting empty as a baseline on all graphs
neg_control_data <- subset(data_design_0803_averages, Guide == "empty")

experimental_data <- subset(data_design_0803_averages, Guide != "empty")
experimental_data$facet <- experimental_data$Guide
baseline_all_facets = merge(neg_control_data, data.frame(Guide = "empty", facet = experimental_data$facet))

data_for_plotting <- rbind(baseline_all_facets, experimental_data)


# plot with averages of replicates + empty on all graphs
gc_averages_0803 <- ggplot(data = data_for_plotting, aes(x=Time, y=Average, color = Group)) +
  geom_line() +
  facet_grid(rows=vars(facet), cols = vars(Vector, ATC_uM),
             labeller = labeller(ATC_uM = ATC_labs, facet = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "Guides 10-26 Growth Assay", caption = "From Aug 3, 2023") +
  theme_bw() +
  theme(strip.text = element_text(face="bold", size = 12),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

# save plot
ggsave("080323_curves_comparison.png", plot = gc_averages_0803)



# dnaA plot
dnaA_plot <- ggplot(data = data_design_0718_dnaA, aes(x=Time, y=Measurements, color = Replicate)) +
  geom_smooth(span=0.15, se=FALSE) +
  facet_grid(rows=vars(Guide), cols = vars(Vector, ATC_uM),
             labeller = labeller(ATC_uM = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "dnaA Growth Assay", caption = "From July 18, 2023") +
  theme_bw() +
  theme(plot.title = element_text(face="bold"),
        strip.text = element_text(face="bold"),
        legend.position = "none")

# fusA plot
fusA_plot <- ggplot(data = data_design_0718_fusA, aes(x=Time, y=Measurements, color = Replicate)) +
  geom_smooth(span=0.15, se=FALSE) +
  facet_grid(rows=vars(Guide), cols = vars(Vector, ATC_uM),
             labeller = labeller(ATC_uM = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "fusA Growth Assay", caption = "From July 18, 2023") +
  theme_bw() +
  theme(plot.title = element_text(face="bold"),
        strip.text = element_text(face="bold"),
        legend.position = "none")

# proS plot
proS_plot <- ggplot(data = data_design_0718_proS, aes(x=Time, y=Measurements, color = Replicate)) +
  geom_smooth(span=0.15, se=FALSE) +
  facet_grid(rows=vars(Guide), cols = vars(Vector, ATC_uM),
             labeller = labeller(ATC_uM = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "proS Growth Assay", caption = "From July 18, 2023") +
  theme_bw() +
  theme(plot.title = element_text(face="bold"),
        strip.text = element_text(face="bold"),
        legend.position = "none")

# ftsB plot
ftsB_plot <- ggplot(data = data_design_0718_ftsB, aes(x=Time, y=Measurements, color = Replicate)) +
  geom_smooth(span=0.15, se=FALSE) +
  facet_grid(rows=vars(Guide), cols = vars(Vector, ATC_uM),
             labeller = labeller(ATC_uM = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)", 
       title = "ftsB Growth Assay", caption = "From July 18, 2023") +
  theme_bw() +
  theme(plot.title = element_text(face="bold"),
        strip.text = element_text(face="bold"),
        legend.position = "none")

# arrange to put all four plots together in the same image
all_genes_plots <- ggarrange(dnaA_plot, fusA_plot, proS_plot, ftsB_plot, nrow =2, ncol = 2)

# save plots as png
ggsave("071823_growthcurve_bygene.png", plot = all_genes_plots)

```


## Calculate lag time, max growth rate, area under curve (total growth)

```{r}
# calculate per capita derivative
# include trans_y and window_width_n for smoothing if data is really "jumpy" (may not be needed)
data_design_0726_filtered <- data_design_0726_filtered %>%
  group_by(Well, Guide, ATC_uM, Vector, Gene, Replicate) %>%
  mutate(deriv_percap = calc_deriv(x=Time, y=Measurements, percapita = T, blank = 0,
                                   window_width_n=5, trans_y="log")) %>%
  ungroup()


# plot per capita derivatives
ggplot(data=data_design_0726_filtered, aes(x=Time, y=deriv_percap)) +
  geom_line() +
  facet_wrap(~Well+file, scales="free")

# calculate lag time, maximum growth rate, time at maximum growth rate, area under curve
# group by all variables so that you end up with one row per well
# make sure not to group by anything that varies within a well
data_0726_sum <- data_design_0726_filtered %>%
  group_by(file, Well, Guide, ATC_uM, Vector, Replicate, Gene, PAM) %>%
  summarize(min_dens = first_minima(Measurements, return="y"), # use for calculating lag time
    lag_time = lag_time(y=Measurements, x=Time, deriv = deriv_percap, y0 = min_dens), # lag time
    max_growth_rate = max_gc(deriv_percap, na.rm=T), # maximum growth rate
    time_max_growth = extr_val(Time, which_max_gc(deriv_percap)), # time at maximum growth rate
    area_under_curve = auc(x=Time, y=Measurements)) %>% # area under curve
  ungroup()

# plot lag time
lagtime_plot_0726 <- ggplot(data_0726_sum, aes(x=ATC_uM, y=lag_time, color = ATC_uM)) +
  geom_point() +
  facet_grid(rows = vars(Gene), cols = vars(Vector, PAM),
             labeller = labeller(Guide = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Lag Time (Hours)", 
       title = "Lag Time for Guides 14-26 Growth Assay", caption = "From July 26, 2023") +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

ggsave("072623_lagTimePlot.png", plot = lagtime_plot_0726)

# plot max growth rate
maxgrowthrate_plot_0726 <- ggplot(data_0726_sum, aes(x=ATC_uM, y=max_growth_rate, color = ATC_uM)) +
  geom_point() +
  facet_grid(rows = vars(Gene), cols = vars(Vector, PAM),
             labeller = labeller(Guide = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Maximum Growth Rate", 
       title = "Maximum Growth Rates for Guides 14-26 Growth Assay", caption = "From July 26, 2023") +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

ggsave("072623_maxGrowthRatePlot.png", plot = maxgrowthrate_plot_0726)

# plot area under curve
auc_plot_0726 <- ggplot(data_0726_sum, aes(x=ATC_uM, y=area_under_curve, color = ATC_uM)) +
  geom_point() +
  facet_grid(rows = vars(Gene), cols = vars(Vector, PAM),
             labeller = labeller(Guide = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Area Under Curve", 
       title = "Area Under Curve for Guides 14-26 Growth Assay", caption = "From July 26, 2023") +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

ggsave("072623_areaUnderCurvePlot.png", plot = auc_plot_0726)


# average out replicates
data_0726_sum_avg <- data_0726_sum %>%
  group_by(file, Guide, ATC_uM, Vector, Gene, PAM) %>%
  summarize(lag_time_avg = mean(lag_time),
            max_growth_rate_avg = mean(max_growth_rate),
            auc_avg = mean(area_under_curve)) %>%
  ungroup() %>%
  mutate(Group = case_when(Guide == "empty" ~ "Empty",
                           Guide != "empty" ~ "Experimental"))

# create dataset that will allow for plotting empty as a baseline on all graphs
neg_control_avg_data <- subset(data_0726_sum_avg, Guide == "empty")

experimental_avg_data <- subset(data_0726_sum_avg, Guide != "empty")
experimental_avg_data$facet <-experimental_avg_data$Guide
baseline_all_facets_sum = merge(neg_control_avg_data, data.frame(Guide = "empty", facet = experimental_avg_data$facet))

plot_data_sum <- rbind(baseline_all_facets_sum, experimental_avg_data)

# lag time plot w baseline
lagtime_plot_avg_0726 <- ggplot(plot_data_sum, aes(x = ATC_uM, y= lag_time_avg, color = Group)) +
  geom_point() +
  facet_grid(rows = vars(facet),
             labeller = labeller(facet = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Lag Time (Hours)", 
       title = "Lag Time",) +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

ggsave("072623_lagtimeplot_avg.png", plot = lagtime_plot_avg_0726)

# max growth rate plot w baseline
maxgrowthrate_plot_avg_0726 <- ggplot(plot_data_sum, aes(x=ATC_uM, y=max_growth_rate_avg, color = Group)) +
  geom_point() +
  facet_grid(rows = vars(facet),
             labeller = labeller(facet = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Maximum Growth Rate", 
       title = "Maximum Growth Rate") +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

ggsave("072623_maxGrowthRatePlot_avg.png", plot = maxgrowthrate_plot_avg_0726)

# area under curve plot w baseline
auc_plot_avg_0726 <- ggplot(plot_data_sum, aes(x=ATC_uM, y=auc_avg, color = Group)) +
  geom_point() +
  facet_grid(rows = vars(facet),
             labeller = labeller(facet = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Area Under Curve", 
       title = "Area Under Curve") +
  theme(strip.text = element_text(face="bold", size = 14),
        title = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 12))

ggsave("072623_areaUnderCurvePlot_avg.png", plot = auc_plot_avg_0726)


all_genes_plots <- ggarrange(dnaA_plot, fusA_plot, proS_plot, ftsB_plot, nrow =2, ncol = 2)

summarized_metrics <- ggarrange(lagtime_plot_avg_0726, maxgrowthrate_plot_avg_0726, auc_plot_avg_0726, nrow = 1, ncol = 3, 
                                common.legend = T, legend = "right")

summarized_metrics <- annotate_figure(summarized_metrics, fig.lab = "From July 26, 2023", fig.lab.pos = "bottom.right",
                                      fig.lab.face = "bold", fig.lab.size = 12)

ggsave("072623_metrics_avg.jpg", plot = summarized_metrics)
```


