---
title: "growth_curve_analysis_062723"
author: "Sierra Mellor"
date: "2023-06-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r, echo=FALSE}
library(gcplyr)
library(dplyr)
library(ggplot2)
library(lubridate)
```

## Import and Transform Data

```{r}
# import data as wide format
wide_data_0627 <- read_wides("ftsZpidSpryC_growthCurves_06282023_cleanData.csv")
#str(wide_data_0627)
head(wide_data_0627)

# transform to tidy format
tidy_data_0627 <- trans_wide_to_tidy(
  wides = wide_data_0627,
  id_cols = c("file", "Time", "Temp"))
str(tidy_data_0627)
head(tidy_data_0627)
```

## Create Design Information

```{r}
design_0627 <- read_tidys("062823_growthCurve_design.csv")
head(design_0627)

```

## Merge and Clean up Data

```{r}
# merge data and design data frames
data_design_merged_0627 <- merge_dfs(tidy_data_0627, design_0627)
str(data_design_merged_0627)
head(data_design_merged_0627)

# convert time to numeric
data_design_merged_0627$Time <- time_length(hms(data_design_merged_0627$Time), unit = "hour")
head(data_design_merged_0627)

# reorder Well and Guide levels
data_design_merged_0627$Well <- factor(data_design_merged_0627$Well,
                                       levels=paste(rep(LETTERS[1:8], each=12), 1:12, sep=""))
data_design_merged_0627$Guide <- factor(data_design_merged_0627$Guide,
                                        levels=c("empty", "10", "11", "12", "13"))

# omit NA wells
data_design_merged_0627 <- data_design_merged_0627 %>%
  filter(!is.na(Guide))
str(data_design_merged_0627)
```

## Plot Curves

```{r}
# labels for ATC concentration
ATC_labs <- c("0 uM", "0.4 uM", "1 uM")
names(ATC_labs) <- c("0", "0.4", "1")

guide_labs <- c("Empty", "Guide 10 (NGG)", "Guide 11 (NAN)", "Guide 12 (NAN)", "Guide 13 (NNN)")
names(guide_labs) <- c("empty", "10", "11", "12", "13")

ggplot(data = data_design_merged_0627, aes(x=Time, y=Measurements, color=uM_ATC)) +
  geom_line() +
  facet_wrap(~Well, nrow = 8, ncol = 12)

ggplot(data = data_design_merged_0627, aes(x=Time, y=Measurements, color=Replicate)) +
  geom_line() +
  facet_grid(rows=vars(Guide), cols = vars(Plasmid, uM_ATC), 
             labeller = labeller(uM_ATC = ATC_labs, Guide = guide_labs)) +
  labs(y = "OD 600", x = "Time (hours)") +
  theme_bw() 

ggplot(data = data_design_merged_0627, aes(x=Time, y=Measurements, color=Replicate)) +
  geom_line() +
  facet_grid(rows=vars(Guide, Plasmid), cols = vars(uM_ATC))
```


## Calculate lag time, max growth rate, area under curve (total growth)

```{r}
# calculate per capita derivative
data_design_merged_0627 <-  data_design_merged_0627 %>%
  group_by(Well, Guide, uM_ATC, Plasmid, Replicate) %>%
  mutate(deriv_percap = calc_deriv(x=Time, y=Measurements, percapita = TRUE, blank = 0))

# plot per capita derivatives
ggplot(data=data_design_merged_0627, aes(x=Time, y=deriv_percap)) +
  geom_line() +
  facet_wrap(~Well, scales="free")

# calculate lag time, maximum growth rate, time at maximum growth rate, area under curve
# group by all variables so that you end up with one row per well
# make sure not to group by anything that varies wtihin a well
data_0627_sum <- data_design_merged_0627 %>%
  group_by(Well, Guide, uM_ATC, Plasmid, Replicate) %>%
  summarize(min_dens = first_minima(Measurements, return="y"), # use for lag time
    lag_time = lag_time(y=Measurements, x=Time, deriv = deriv_percap, y0 = min_dens),
    max_growth_rate = max_gc(deriv_percap, na.rm=T),
    time_max_growth = extr_val(Time, which_max_gc(deriv_percap)),
    area_under_curve = auc(x=Time, y=Measurements))

# plot lag time
ggplot(data_0627_sum, aes(x=uM_ATC, y=lag_time, color = uM_ATC)) +
  geom_point() +
  facet_grid(rows = vars(Plasmid), cols = vars(Guide),
             labeller = labeller(Guide = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Lag Time (Hours)", title = "Lag Time for Guides 10-13")

# plot max growth rate
ggplot(data_0627_sum, aes(x=uM_ATC, y=max_growth_rate, color = uM_ATC)) +
  geom_point() +
  facet_grid(rows = vars(Plasmid), cols = vars(Guide),
             labeller = labeller(Guide = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Maximum Growth Rate", title = "Maximum Growth Rates for Guides 10-13")

# plot area under curve
ggplot(data_0627_sum, aes(x=uM_ATC, y=area_under_curve, color = uM_ATC)) +
  geom_point() +
  facet_grid(rows = vars(Plasmid), cols = vars(Guide),
             labeller = labeller(Guide = guide_labs)) +
  theme_bw() +
  labs(x="ATC Concentration (uM)", y = "Area Under Curve", title = "Area Under Curve for Guides 10-13 Growth Assay")
```


